Back-End/TestCoreAPI/Controllers/FamilyMemberController.cs

familymember id

---

Front-End/src/App.js
Front-End/src/Components/Login/ForgotPassword.jsx
Front-End/src/Components/Login/Login.css
Front-End/src/Components/Login/Login.jsx
Front-End/src/Components/Login/Registration.jsx
Front-End/src/Components/Sidebar.jsx

All Icon Change

---

Back-End/TestCoreAPI/Controllers/FamilyMemberController.cs
Back-End/TestCoreAPI/Controllers/UserController.cs

Birthdate remove

---

Front-End/src/Components/Login/ForgotPassword.jsx
Front-End/src/Components/Login/Registration.jsx
Front-End/src/Components/Pages/DisplayCategory.jsx
Front-End/src/Components/Pages/Familydetail.css
Front-End/src/Components/Pages/Familydetail.jsx
Front-End/src/Components/Pages/JsonData.jsx
Front-End/src/Components/Sidebar.jsx

Edit-Validation

---

TestCoreAPI/Controllers/AdminTeacherController.cs
TestCoreAPI/Controllers/FeesController.cs
TestCoreAPI/Controllers/StandardController.cs
TestCoreAPI/CreateModel/FeesCreate.cs
TestCoreAPI/CreateModel/StandardCreate.cs
TestCoreAPI/Dtos/FeesDto.cs
TestCoreAPI/Dtos/StandardDto.cs
TestCoreAPI/Mapper/AdminTeacherMapper.cs
TestCoreAPI/Mapper/FeesMapper.cs
TestCoreAPI/Mapper/StandardMapper.cs

Standard controller

---

TestCoreAPI/Controllers/AdminTeacherController.cs
TestCoreAPI/Controllers/SubjectController.cs
TestCoreAPI/CreateModel/SubjectCreate.cs
TestCoreAPI/Dtos/SubjectDto.cs
TestCoreAPI/Mapper/SubjectMapper.cs
TestCoreAPI/TestCoreApi.csproj
TestCoreAPI/appsettings.json

Subject Controller

---

TestCoreAPI/Controllers/StudentController.cs
TestCoreAPI/CreateModel/FamilyCreate.cs
TestCoreAPI/CreateModel/StudentCreate.cs
TestCoreAPI/Dtos/StudentDto.cs
TestCoreAPI/Mapper/StudentMapper.cs
TestCoreAPI/appsettings.json

Student Controller

---

TestCoreAPI/Controllers/StudentController.cs

updated Student Controller

---

TestCoreAPI/Controllers/AdminTeacherController.cs
TestCoreAPI/Mapper/FeesMapper.cs
TestCoreAPI/Mapper/StandardMapper.cs
TestCoreAPI/RequestModel/LoginRequestModel.cs
TestCoreAPI/appsettings.json

Admin Teacher Controller IsLogin

Admin Teacher Controller IsLogin

---

TestCoreAPI/Controllers/TimeTableController.cs
TestCoreAPI/appsettings.json

Get in TimeTable Controller

---

TestCoreAPI/Controllers/FamilyController.cs
TestCoreAPI/Controllers/FeesController.cs
TestCoreAPI/Mapper/FamilyMapper.cs
TestCoreAPI/appsettings.json

Family controller update

---

TestCoreAPI/Mapper/StudentMapper.cs
TestCoreAPI/Models/Standard.cs
TestCoreAPI/appsettings.json

BloodGroup

---

TestCoreAPI/Controllers/AdminTeacherController.cs
TestCoreAPI/Controllers/FamilyController.cs
TestCoreAPI/Controllers/StandardController.cs
TestCoreAPI/Mapper/AdminTeacherMapper.cs
TestCoreAPI/Mapper/FamilyMapper.cs
TestCoreAPI/Mapper/StandardMapper.cs
TestCoreAPI/UpdateModel/AdminTeacherUpdate.cs
TestCoreAPI/UpdateModel/FamilyUpdate.cs
TestCoreAPI/UpdateModel/FeesUpdate.cs
TestCoreAPI/UpdateModel/StandardUpdate.cs
TestCoreAPI/appsettings.json

Put method with update model

---

TestCoreAPI/CreateModel/StudentCreate.cs
TestCoreAPI/Data/StudentsAPIDbContext.cs
TestCoreAPI/Dtos/StudentDto.cs
TestCoreAPI/Mapper/StudentMapper.cs
TestCoreAPI/Migrations/20240321112820_AddFeesMaster.Designer.cs
TestCoreAPI/Migrations/20240321112820_AddFeesMaster.cs
TestCoreAPI/Models/FeesMaster.cs
TestCoreAPI/Models/Student.cs

Added FeesMaster

---

TestCoreAPI/CreateModel/AdminTeacherCreate.cs
TestCoreAPI/Data/StudentsAPIDbContext.cs
TestCoreAPI/Dtos/AdminTeacherDto.cs
TestCoreAPI/Mapper/AdminTeacherMapper.cs
TestCoreAPI/Migrations/20240322113039_AddSubjectEntityEntries.Designer.cs
TestCoreAPI/Migrations/20240322113039_AddSubjectEntityEntries.cs
TestCoreAPI/Migrations/20240322114532_RenameSubjectEntry.Designer.cs
TestCoreAPI/Migrations/20240322114532_RenameSubjectEntry.cs
TestCoreAPI/Models/AdminTeacher.cs
TestCoreAPI/Models/Standard.cs

Added SubjectEntityEntry Migration

Added SubjectEntityEntry Migration

---

TestCoreAPI/Controllers/DropDownController.cs
TestCoreAPI/Controllers/StandardController.cs
TestCoreAPI/Controllers/TimeTableController.cs
TestCoreAPI/CreateModel/TimeTableCreate.cs
TestCoreAPI/Mapper/TimeTableMapper.cs

Add DropDown Controller

---

TestCoreAPI/Controllers/AdminTeacherController.cs
TestCoreAPI/RequestModel/PasswordRequestModel.cs

ChangePassword From BackEnd and Create PasswordRequestModel

ChangePassword From BackEnd 

---

TestCoreAPI/Controllers/FeesController.cs
TestCoreAPI/CreateModel/FeesCreate.cs
TestCoreAPI/Dtos/FeesDto.cs
TestCoreAPI/Mapper/FeesMapper.cs
TestCoreAPI/Migrations/20240322110532_AddFeesFrequncy.Designer.cs
TestCoreAPI/Migrations/20240322110532_AddFeesFrequncy.cs
TestCoreAPI/Models/Fees.cs

AddFeesByStudentId

---

TestCoreAPI/Controllers/AdminTeacherController.cs

ChangePassword Method Changes

---

TestCoreAPI/Controllers/AdminTeacherController.cs
TestCoreAPI/CreateModel/AdminTeacherCreate.cs

Admin teacher controller subject id student id change

Admin teacher controller subject id student id change

---

TestCoreAPI/Controllers/AdminTeacherController.cs

LoginTime Pass Id

---

TestCoreAPI/Controllers/AdminTeacherController.cs

add filter on registration

---

TestCoreAPI/Controllers/TimeTableController.cs

PostMethod List Add

---

TestCoreAPI/Controllers/AdminTeacherController.cs

AdminTeacher- AddFilter in post

AdminTeacher- AddFilter in post

---

TestCoreAPI/Controllers/AdminTeacherController.cs

Bug Fixed in AdminTeacher Post

Bug Fixed in AdminTeacher Post

---

TestCoreAPI/Controllers/AdminTeacherController.cs

Remove Duplicate Files in AdminTeacher Controller Post

Remove Duplicate Files in AdminTeacher Controller Post

---

TestCoreAPI/Controllers/StudentController.cs
TestCoreAPI/Controllers/TimeTableController.cs

Update Student Controller StandardId and TimeTable Controller Add Array

Update Student Controller StandardId and TimeTable Controller Add Array
